# Exercise 9

## Mashable news stories analysis

Predicting if a news story is going to be popular


In [190]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/albahnsen/PracticalMachineLearningClass/master/datasets/mashable.csv'
train_df = pd.read_csv(url, index_col=0)
train_df.head()

url  timedelta  \
0  http://mashable.com/2014/12/10/cia-torture-rep...       28.0   
1  http://mashable.com/2013/10/18/bitlock-kicksta...      447.0   
2  http://mashable.com/2013/07/24/google-glass-po...      533.0   
3  http://mashable.com/2013/11/21/these-are-the-m...      413.0   
4  http://mashable.com/2014/02/11/parking-ticket-...      331.0   

   n_tokens_title  n_tokens_content  n_unique_tokens  n_non_stop_words  \
0             9.0             188.0         0.732620               1.0   
1             7.0             297.0         0.653199               1.0   
2            11.0             181.0         0.660377               1.0   
3            12.0             781.0         0.497409               1.0   
4             8.0             177.0         0.685714               1.0   

   n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  num_imgs   ...     \
0                  0.844262        5.0             1.0       1.0   ...      
1                  0.815789        9.0             4.0       1.0   ...      
2                  0.775701        4.0             3.0       1.0   ...      
3                  0.677350       10.0             3.0       1.0   ...      
4                  0.830357        3.0             2.0       1.0   ...      

   min_positive_polarity  max_positive_polarity  avg_negative_polarity  \
0               0.200000                   0.80              -0.487500   
1               0.160000                   0.50              -0.135340   
2               0.136364                   1.00               0.000000   
3               0.100000                   1.00              -0.195701   
4               0.100000                   0.55              -0.175000   

   min_negative_polarity  max_negative_polarity  title_subjectivity  \
0                  -0.60              -0.250000                 0.9   
1                  -0.40              -0.050000                 0.1   
2                   0.00               0.000000                 0.3   
3                  -0.40              -0.071429                 0.0   
4                  -0.25              -0.100000                 0.0   

   title_sentiment_polarity  abs_title_subjectivity  \
0                       0.8                     0.4   
1                      -0.1                     0.4   
2                       1.0                     0.2   
3                       0.0                     0.5   
4                       0.0                     0.5   

   abs_title_sentiment_polarity  Popular  
0                           0.8        1  
1                           0.1        0  
2                           1.0        0  
3                           0.0        0  
4                           0.0        0  

[5 rows x 61 columns]

In [191]:
train_df.shape

(6000, 61)

In [192]:
X = train_df.drop(['url', 'Popular'], axis=1)
y = train_df['Popular']

In [193]:
y.mean()

0.5

In [194]:
# train/test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Exercise 9.1

Estimate a Decision Tree Classifier and a Logistic Regresion

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [195]:
#Decision Tree Classifier 
from sklearn.tree import DecisionTreeClassifier
treeclf = DecisionTreeClassifier()
treeclf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [196]:
from sklearn.metrics import accuracy_score
from sklearn import metrics
treeclf.score(X_test, y_test)
y_pred=treeclf.predict(X_test)
print(f"Accuracy Score: {round(accuracy_score(y_test, y_pred),3)}")
print(f"F1 Score:{round(f1_score(y_pred, y_test),3)}")

Accuracy Score: 0.551
F1 Score:0.552


In [197]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e9, solver='liblinear', multi_class='ovr')
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)
print(f"Accuracy Score: {round(accuracy_score(y_test, y_pred_logreg),3)}")
print(f"F1 Score:{round(f1_score(y_pred_logreg, y_test),3)}")

Accuracy Score: 0.627
F1 Score:0.61


# Exercise 9.2

Estimate 300 bagged samples

Estimate the following set of classifiers:

* 100 Decision Trees where max_depth=None
* 100 Decision Trees where max_depth=2
* 100 Logistic Regressions

In [198]:
# set a seed for reproducibility
np.random.seed(123)

n_samples = train_df.shape[0]
n_B = 100

# create ten bootstrap samples (will be used to select rows from the DataFrame)
samples = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
samples

[array([3582, 3454, 1346, ..., 3447, 4777, 2770]),
 array([4620, 2546,  261, ...,  720, 2868, 4917]),
 array([5307,  594,  925, ...,  615, 1490, 3208]),
 array([4288, 2101, 4399, ..., 3458, 5177, 5219]),
 array([3131, 3822, 2323, ..., 5651,  600, 1805]),
 array([ 138, 1400,  803, ..., 2648, 4349, 5664]),
 array([5238,  630,  273, ..., 4814, 5828,  881]),
 array([2123, 4123, 5343, ..., 1651, 4474, 5586]),
 array([ 746, 4683,  513, ...,  710, 3553, 2096]),
 array([2467, 5108, 5052, ..., 3728, 5389, 4002]),
 array([2781, 1976, 4193, ..., 5248, 2939, 4780]),
 array([4240, 5109, 5901, ..., 1458, 2370, 2017]),
 array([ 624, 1531, 4806, ..., 4399, 1262, 5119]),
 array([2085, 3779, 1301, ..., 5613, 2635, 2590]),
 array([4143, 4896, 3125, ...,  953, 1640, 3983]),
 array([5962, 4997, 1412, ..., 3863, 3002,  436]),
 array([4868, 3275, 5541, ..., 3911, 1983,  124]),
 array([2633, 3671, 5680, ..., 2780, 1403, 4215]),
 array([2760,  765,  115, ..., 5250, 5560, 1993]),
 array([4377, 5845, 3747, ..., 

In [199]:
# set a seed for reproducibility
np.random.seed(125)

n_samples1 = train_df.shape[0]
n_B1 = 100

# create ten bootstrap samples (will be used to select rows from the DataFrame)
samples1 = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
samples1

[array([3005, 2205, 5346, ...,  700, 1855,  828]),
 array([1933, 2512, 2845, ..., 3736, 1097, 3027]),
 array([3415, 5428, 2048, ..., 4098, 5701, 2674]),
 array([1878, 3948, 1726, ..., 3904, 1051, 3432]),
 array([ 394, 3206,  459, ..., 2624, 2862, 5873]),
 array([5247, 1212, 1842, ...,  971, 1408,  780]),
 array([5178,  303, 2671, ...,  378, 3104, 1919]),
 array([5386, 2725,  116, ..., 1359,  457, 2170]),
 array([ 833, 4944,  933, ..., 2659, 5021,  373]),
 array([ 226, 4979,  515, ..., 1489,  949, 4391]),
 array([2261, 2051, 4722, ...,  697, 2525, 3145]),
 array([2701, 4694, 4501, ...,  293, 4122,  696]),
 array([  84, 1316, 1861, ..., 1372,  441, 2139]),
 array([2101, 3667, 4960, ...,  160, 3161, 1832]),
 array([3289, 3969, 2728, ..., 4658, 4961, 5461]),
 array([2900, 1289, 4265, ..., 5190, 4762, 5793]),
 array([3398,  633, 4648, ..., 3461, 4238, 1051]),
 array([1378, 3857, 2890, ..., 1390, 5039, 5439]),
 array([5235, 4530, 1477, ..., 2206, 1985, 4265]),
 array([5499,  865, 5542, ..., 

In [200]:
# set a seed for reproducibility
np.random.seed(231)

n_samples2 = train_df.shape[0]
n_B2 = 100

# create ten bootstrap samples (will be used to select rows from the DataFrame)
samples2 = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
samples2

[array([1200, 4806, 3586, ..., 1407, 3443,  840]),
 array([5704,  517, 5344, ..., 5328, 1341, 3788]),
 array([3259, 2367, 1487, ..., 1098, 3150, 3869]),
 array([4694, 4642,  115, ..., 4676, 5905, 5148]),
 array([4025, 3690, 1399, ..., 1458, 2641,  592]),
 array([ 746, 3223, 4089, ..., 3102, 5181, 3400]),
 array([3673,  965, 4739, ..., 4882, 2794, 3399]),
 array([1898, 5776, 3012, ..., 4932, 4865, 2830]),
 array([2254, 4181, 1184, ...,  378, 5849, 2294]),
 array([2493,  235,  455, ..., 3253, 2078, 4527]),
 array([ 708,  988, 3108, ..., 5338, 2870, 1965]),
 array([1705, 4897, 4371, ..., 2435, 1844, 1288]),
 array([2239, 1104,  247, ..., 2821, 3150, 5608]),
 array([ 136, 4493,  747, ...,  990, 1478, 3612]),
 array([ 226, 5672, 4269, ..., 5753, 2472, 4663]),
 array([1537, 5168, 4158, ..., 1961, 3022, 3024]),
 array([3098, 1912, 2674, ..., 2319, 3097, 5738]),
 array([4880, 1064, 2924, ..., 5803, 3507, 1962]),
 array([4358, 4861,  479, ...,  871, 2854, 2896]),
 array([1356, 5884,  586, ..., 

In [201]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import BaggingClassifier

In [202]:
models = {'log': LogisticRegression(solver='liblinear',C=1e9, random_state=123),
          'dt1': DecisionTreeClassifier(max_depth=None, random_state=125),
          'dt2': DecisionTreeClassifier(max_depth=2, random_state=213)}

In [203]:
y_pred = pd.DataFrame (columns =models.keys(),index= y_test.index )

In [204]:
#for tp in models.keys():
for i, model  in models.items():
       
    bagreg = BaggingClassifier(model, n_estimators=100,bootstrap=True, oob_score=True, random_state=1,n_jobs=-1)
    
    bagreg.fit(X_train, y_train)
    
    y_pred[i] = bagreg.predict(X_test)


In [205]:
y_pred

log  dt1  dt2
1483    1    1    1
2185    1    1    1
2520    1    1    1
3721    1    1    1
3727    0    0    0
4524    0    1    1
234     0    0    0
4735    0    0    0
5839    0    0    0
2939    1    0    1
3053    1    1    1
867     1    1    1
276     1    1    1
5798    0    0    0
3512    1    1    1
5789    0    0    0
3198    1    1    1
5908    1    1    1
5718    0    1    0
2687    0    0    0
250     0    1    1
5461    1    1    1
3052    0    0    0
2711    0    1    1
3771    0    0    0
5988    0    0    0
5645    0    1    0
4617    0    0    0
368     1    0    1
4916    0    0    0
...   ...  ...  ...
19      0    0    0
4088    1    1    1
1395    1    1    1
2576    0    0    0
2878    0    0    0
3147    0    0    0
4513    0    0    0
1620    0    1    1
4522    1    1    1
5485    1    1    1
2394    0    0    0
1691    0    0    0
4949    0    0    0
2805    0    1    1
494     1    1    1
5287    0    0    0
3316    0    0    1
3176    1    0    1
2372    1    1    1
5947    1    1    1
5782    0    0    0
1814    0    0    0
4704    0    0    0
5333    0    0    0
946     0    1    1
3077    0    1    1
5166    0    0    0
2227    1    1    1
5684    0    0    0
1937    0    0    0

[1500 rows x 3 columns]

In [206]:
print('LogReg')
print(f"Accuracy Score: {round(accuracy_score(y_test, y_pred.iloc[:,0]),3)}")
print(f"F1 Score:{round(f1_score(y_test,y_pred.iloc[:,0]),3)}")
print(' ')
print('Tree1 max_depth=None')
print(f"Accuracy Score: {round(accuracy_score(y_test, y_pred.iloc[:,1]),3)}")
print(f"F1 Score:{round(f1_score(y_test,y_pred.iloc[:,1]),3)}")
print(' ')
print('Tree1 max_depth=2')
print(f"Accuracy Score: {round(accuracy_score(y_test, y_pred.iloc[:,2]),3)}")
print(f"F1 Score:{round(f1_score(y_test,y_pred.iloc[:,2]),3)}")

LogReg
Accuracy Score: 0.625
F1 Score:0.607
 
Tree1 max_depth=None
Accuracy Score: 0.639
F1 Score:0.636
 
Tree1 max_depth=2
Accuracy Score: 0.645
F1 Score:0.643


# Exercise 9.3

Ensemble using majority voting

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [106]:
votClass=VotingClassifier(estimators=[('lr',LogisticRegression(random_state=7351)),
                                     ('trcl',DecisionTreeClassifier(random_state=7351)),
                                     ('lr_l1',LogisticRegression(random_state=7351,penalty='l1')),
                                     ('lr_l2',LogisticRegression(random_state=7351,penalty='l2'))],
                                     
                          n_jobs=-1)

In [107]:
votClass.fit(X_train,y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=7351, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)), ('trcl', Decisi...penalty='l2', random_state=7351, solver='warn',
          tol=0.0001, verbose=0, warm_start=False))],
         flatten_transform=None, n_jobs=-1, voting='hard', weights=None)

In [136]:
y_pred=votClass.predict(X_test)
print(f"F1 Score:{round(f1_score(y_test,y_pred),3)}")
print(f"Accuracy Score:{round(accuracy_score(y_test,y_pred),3)}")

F1 Score:0.605
Accuracy Score:0.631


# Exercise 9.4

Estimate te probability as %models that predict positive

Modify the probability threshold and select the one that maximizes the F1-Score

In [135]:
clf=BaggingClassifier(base_estimator=DecisionTreeClassifier(max_depth=2, random_state=123),
                     n_estimators=100, bootstrap=True, random_state=42, n_jobs=-1, oob_score=True)
f=[]
rango=np.arange(0.1,1,0.1)
for j in rango:
    clf.fit(X_train, y_train)
    y_pred=(clf.predict_proba(X_test)[:,1]>=j).astype(int)
    f.append([j,round(f1_score(y_pred, y_test),2), round(clf.score(X_test,y_test),2)])
    
f=pd.DataFrame(f, columns=['prob', 'f1_score', 'Acc_score'])
f.loc[f['f1_score'].idxmax()]

prob         0.40
f1_score     0.70
Acc_score    0.64
Name: 3, dtype: float64

# Exercise 9.5

Ensemble using weighted voting using the oob_error

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [185]:
models=[DecisionTreeClassifier(max_depth=2, random_state=123),DecisionTreeClassifier(max_depth=None, random_state=123),
        LogisticRegression(solver='liblinear',C=1e9, random_state=123),]
print(models)

y_pred_mean=[]
fs=[]
j=1
for model in list(models):
    clf = BaggingClassifier(base_estimator=model,n_estimators=100, bootstrap=True, random_state=42, n_jobs=-1, oob_score=True)
    clf.fit(X_train,y_train)
    errors=np.zeros(clf.n_estimators)
    y_pred_all_=np.zeros((X_test.shape[0],clf.n_estimators))
    for b in range(clf.n_estimators):
        oob_sample = ~clf.estimators_samples_[b]
        y_pred_=clf.estimators_[b].predict(pd.DataFrame(X_train).values[oob_sample])
        errors[b]=metrics.accuracy_score(y_pred_, y_train.values[oob_sample])
        y_pred_all_[:,b]=clf.estimators_[b].predict(X_test)
    alpha=(1-errors)/ (1-errors).sum()
    y_pred=(np.sum(y_pred_all_*alpha, axis=1)>=0.5).astype(np.int)
    y_pred_mean.append([b, y_pred.mean()])
    fs.append([j,round(f1_score(y_pred,y_test),3),round(clf.score(X_test,y_test),3)])
    j=j+1
y_pred_mean=pd.DataFrame(y_pred_mean)
y_pred_mean[1].tolist()
fs = pd.DataFrame(fs, columns=['prob','f1_score','tree_score'])

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=123,
            splitter='best'), DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=123,
            splitter='best'), LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=123,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)]


In [186]:
fs

prob  f1_score  tree_score
0     1     0.645       0.645
1     2     0.651       0.640
2     3     0.611       0.626

# Exercise 9.6

Estimate te probability of the weighted voting

Modify the probability threshold and select the one that maximizes the F1-Score

In [188]:
y_pred_0= np.asarray(y_pred_df[0])
prob_mod1=np.sum(y_pred_0)/y_pred_0.shape[1]
print(prob_mod1)

0.49466666666666664


In [182]:

models=[DecisionTreeClassifier(max_depth=None, random_state=123),DecisionTreeClassifier(max_depth=2, random_state=123),
        LogisticRegression(solver='liblinear',C=1e9, random_state=123)]
print(models)
    
y_pred_mean=[]
y_pred_df=[]
fs=[]
fk=[]
j=1
for model in list(models):
    clf = BaggingClassifier(base_estimator=model,n_estimators=100, bootstrap=True, random_state=42, n_jobs=-1, oob_score=True)
    
    ft=[]
    rango=np.arange(0.3,1,0.1)
    for t in rango:
        clf.fit(X_train, y_train)
        errors=np.zeros(clf.n_estimators)
        y_pred_all_=np.zeros((X_test.shape[0],clf.n_estimators))
        for b in range(clf.n_estimators):
            oob_sample = ~clf.estimators_samples_[b]
            y_pred_=clf.estimators_[b].predict(pd.DataFrame(X_train).values[oob_sample])
            errors[b]=metrics.accuracy_score(y_pred_, y_train.values[oob_sample])
            y_pred_all_[:,b]=clf.estimators_[b].predict(X_test)
        alpha=(1-errors)/ (1-errors).sum()
        y_pred=(np.sum(y_pred_all_*alpha, axis=1)>=t).astype(np.int)
        y_pred_df.append([y_pred])
        y_pred_mean.append([b, y_pred.mean()])
        ft.append([j,round(f1_score(y_pred,y_test),3),round(clf.score(X_test,y_test),3)])
        j=j+1
    ft=pd.DataFrame(ft, columns=['prob','F1_score','tree_score'])
    print(ft)
    fs=ft.loc[ft['F1_score'].idxmax()]
    print(fs)
    fk.append([fk,fs])
    
print(fk)

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=123,
            splitter='best'), DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=123,
            splitter='best'), LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=123,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)]
   prob  F1_score  tree_

# Exercise 9.7

Estimate a logistic regression using as input the estimated classifiers

Modify the probability threshold such that maximizes the F1-Score

In [183]:
models=[LogisticRegression(solver='liblinear',C=1e9, random_state=123)]
print(models)
    
y_pred_mean=[]
y_pred_df=[]
fs=[]
fk=[]
j=1
for model in list(models):
    clf = BaggingClassifier(base_estimator=model,n_estimators=100, bootstrap=True, random_state=42, n_jobs=-1, oob_score=True)
    
    ft=[]
    rango=np.arange(0.3,1,0.1)
    for t in rango:
        clf.fit(X_train, y_train)
        errors=np.zeros(clf.n_estimators)
        y_pred_all_=np.zeros((X_test.shape[0],clf.n_estimators))
        for b in range(clf.n_estimators):
            oob_sample = ~clf.estimators_samples_[b]
            y_pred_=clf.estimators_[b].predict(pd.DataFrame(X_train).values[oob_sample])
            errors[b]=metrics.accuracy_score(y_pred_, y_train.values[oob_sample])
            y_pred_all_[:,b]=clf.estimators_[b].predict(X_test)
        alpha=(1-errors)/ (1-errors).sum()
        y_pred=(np.sum(y_pred_all_*alpha, axis=1)>=t).astype(np.int)
        y_pred_df.append([y_pred])
        y_pred_mean.append([b, y_pred.mean()])
        ft.append([j,round(f1_score(y_pred,y_test),3),round(clf.score(X_test,y_test),3)])
        j=j+1
    ft=pd.DataFrame(ft, columns=['prob','F1_score','tree_score'])
    print(ft)
    fs=ft.loc[ft['F1_score'].idxmax()]
    print(fs)
    fk.append([fk,fs]) 
print(fk)

[LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=123,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)]
   prob  F1_score  tree_score
0     1     0.621       0.626
1     2     0.613       0.626
2     3     0.611       0.626
3     4     0.598       0.626
4     5     0.589       0.626
5     6     0.579       0.626
6     7     0.561       0.626
prob          1.000
F1_score      0.621
tree_score    0.626
Name: 0, dtype: float64
[[[...], prob          1.000
F1_score      0.621
tree_score    0.626
Name: 0, dtype: float64]]
